<?php
/**
 * @file
 * Code for the Bundles feature.
 */

include_once 'hr_bundles.features.inc';

/**
 * Get operation from bundle GID
 */
function _hr_bundles_get_operation($gid) {
  $og_groups = entity_load('node', array($gid));
  $og_group = $og_groups[$gid];
  if ($og_group->type == 'hr_bundle') {
    $operations = og_get_entity_groups('node', $og_group);
    if (isset($operations['node']) && count($operations['node'])) {
      return array_pop($operations['node']);
    }
    else {
      return 0;
    }
  }
  else {
    return 0;
  }
}

/**
 * Implements hook_og_context_negotiation_info().
 */
function hr_bundles_og_context_negotiation_info() {
  $providers = array();

  $providers['hr_bundle'] = array(
    'name' => t('Bundle'),
    'description' => t('Select groups if they were passed in the node create URL (e.g. node/add/post?og_group_ref=4,5,6). <em>Note: Depends on <a href="@url">Entity reference prepopulate</a> module, and enabling "Prepopulate" in the field settings.</em>', array('@url' => 'http://drupal.org/project/entityreference_prepopulate')),
    'callback' => 'hr_bundle_og_context_handler',
    'menu path' => array('node/%', 'group/%/%/admin'),
  );
  return $providers;
}

function hr_bundle_og_context_handler($node = NULL) {
  $context = og_context_handler_node($node);
  if (!empty($context) && isset($context['node'][0])) {
    $gid = $context['node'][0];
    $op_gid = _hr_bundles_get_operation($gid);
    if (!empty($op_gid)) {
      $context['node'][0] = $op_gid;
    }
  }
  return $context;
}
